language: generic
sudo: required

before_script:
- ./01_setup.py

script:
- ./02_make_addons.sh

before_deploy:
- cat z-coderdojo.squashfs > /home/travis/z-coderdojo.squashfs

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: "j5Cc89q9xt8un9KU5XcR5UzcrRBOibKO1ZiHyI6AgAJSpN/u90YP8zPNZduF1Eh6k9FUQz9UvGadaGxBkw6CMnMMVF5Hy0J3sIjwI5ulnKSaJoo0sqZDiWJABgJDmtgnSdWBIDnQX3sYUki3vPrujbI2nCfzRPMeju/vszBhW0BgxEBf+T4jmJiyB0B0kFTPaRlkEM1PX1dYp7LmlWmWsPo7accd0DphWDeJiPZjph/80SDvDlY6WqLkjpi6hJtGIfxpGOhjbP+eBl2rXtz+QrKMf5GOmVeRKJXNkV7UsrOAIo0ot5Uy0Bk4SyXulo1rMFxOGz3IirQ45snvjHiJk8IZzmEoa8P55k3q6oTSyaAKDpiLoOKP8jsJajzaGKPmyRDA8W809mE0YsuG8StaWEohknoQovPZTgMMX/1+VAHcl2NEmNcVyyAmdI10N17aTwtVjX3bM+eV1mot19nkPUrK4ZuiobGBTdJvWKhil0IpTwq0L1hPU+ICZKe5S52m8t98pUx1NSbRofIZvD6MQ6YVDxcIzIZHgzjWyYduw1Oevh+M+cn5bMbRf6ur/9XDAx5QSW764OhjjBSJjlM93i2jzdLVjSk+ADhHH+KkYH90rxZn642IIVG8iyu5Ryxs97nAxvrOQ2bLFF1hWhhs1Ud9Tlv3Ie7Jk7FLnZRVN+0="
    file: /home/travis/z-coderdojo.squashfs
